// src/config/constants.js

export const COOKIE_OPTIONS = {
  REFRESH_TOKEN: 'docshield_refresh_token',
};

export const REFRESH_COOKIE_CONFIG = {
  httpOnly: true,
  secure: process.env.NODE_ENV === 'production',
  sameSite: 'lax',
  path: '/api/v1/auth',
  maxAge: 7 * 24 * 60 * 60 * 1000, // 7 days
};

export const PASSWORD_REGEX = /^.{8,}$/;
export const PASSWORD_REQUIREMENT_MSG = 'Password must be at least 8 characters long.';

export const TAMPERING_CATEGORIES = {
  PHOTO_SUBSTITUTION: 'PHOTO_SUBSTITUTION',
  TEXT_ALTERATION: 'TEXT_ALTERATION',
  COMPRESSION_ANOMALY: 'COMPRESSION_ANOMALY',
  METADATA_MISMATCH: 'METADATA_MISMATCH',
  EDGE_DISCONTINUITY: 'EDGE_DISCONTINUITY',
  FONT_INCONSISTENCY: 'FONT_INCONSISTENCY',
  STAMP_IRREGULARITY: 'STAMP_IRREGULARITY',
  STAMP_FORGERY: 'STAMP_FORGERY',
};

export const FACE_VERIFICATION_STATUSES = {
  MATCH: 'MATCH',
  NO_MATCH: 'NO_MATCH',
  INCONCLUSIVE: 'INCONCLUSIVE',
  NO_FACE_DETECTED: 'NO_FACE_DETECTED',
};

export const RISK_LEVELS = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
};

export const SCREENING_VERDICTS = {
  PASSED: 'PASSED',
  REVIEW_REQUIRED: 'REVIEW_REQUIRED',
  REJECTED: 'REJECTED',
};

export const DOCUMENT_TYPES = {
  PASSPORT: 'PASSPORT',
  VISA: 'VISA',
  NATIONAL_ID: 'NATIONAL_ID',
  DRIVING_LICENSE: 'DRIVING_LICENSE',
  PERMIT: 'PERMIT',
  OTHER: 'OTHER',
};

export const DOCUMENT_STATUSES = {
  ACTIVE: 'ACTIVE',
  ARCHIVED: 'ARCHIVED',
  DELETED: 'DELETED',
  PROCESSING: 'PROCESSING',
};

export const PROCESSING_STATUSES = {
  UPLOADED: 'UPLOADED',
  QUEUED: 'QUEUED',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
};

export const ORGANIZATION_STATUSES = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED',
};

export const UPLOAD_LIMITS = {
  MAX_FILE_SIZE_BYTES: 50 * 1024 * 1024, // 50MB
  ALLOWED_MIME_TYPES: [
    'application/pdf',
    'image/jpeg',
    'image/jpg',
    'image/png',
    'image/webp',
    'image/tiff',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/msword',
  ],
  ALLOWED_EXTENSIONS: ['.pdf', '.jpg', '.jpeg', '.png', '.webp', '.tiff', '.tif', '.docx', '.doc'],
};

export const AUDIT_ACTIONS = {
  // Authentication
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  LOGIN_FAILED: 'LOGIN_FAILED',
  REGISTER: 'REGISTER',
  TOKEN_REFRESH: 'TOKEN_REFRESH',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED: 'PASSWORD_RESET_COMPLETED',
  EMAIL_VERIFICATION_SENT: 'EMAIL_VERIFICATION_SENT',
  EMAIL_VERIFIED: 'EMAIL_VERIFIED',

  // User Management
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DELETED: 'USER_DELETED',
  USER_STATUS_CHANGED: 'USER_STATUS_CHANGED',

  // Organizations & Memberships
  ORGANIZATION_CREATED: 'ORGANIZATION_CREATED',
  ORGANIZATION_UPDATED: 'ORGANIZATION_UPDATED',
  ORGANIZATION_DELETED: 'ORGANIZATION_DELETED',
  MEMBER_ADDED: 'MEMBER_ADDED',
  MEMBER_ROLE_UPDATED: 'MEMBER_ROLE_UPDATED',
  MEMBER_REMOVED: 'MEMBER_REMOVED',
  INVITATION_CREATED: 'INVITATION_CREATED',
  INVITATION_ACCEPTED: 'INVITATION_ACCEPTED',
  INVITATION_REVOKED: 'INVITATION_REVOKED',

  // Documents
  DOCUMENT_CREATED: 'DOCUMENT_CREATED',
  DOCUMENT_VIEWED: 'DOCUMENT_VIEWED',
  DOCUMENT_DOWNLOADED: 'DOCUMENT_DOWNLOADED',
  DOCUMENT_UPDATED: 'DOCUMENT_UPDATED',
  DOCUMENT_VERSION_CREATED: 'DOCUMENT_VERSION_CREATED',
  DOCUMENT_ARCHIVED: 'DOCUMENT_ARCHIVED',
  DOCUMENT_DELETED: 'DOCUMENT_DELETED',
  DOCUMENT_ACCESS_DENIED: 'DOCUMENT_ACCESS_DENIED',

  // Processing & Extractions
  DOCUMENT_PROCESSING_STARTED: 'DOCUMENT_PROCESSING_STARTED',
  DOCUMENT_PROCESSING_COMPLETED: 'DOCUMENT_PROCESSING_COMPLETED',
  DOCUMENT_PROCESSING_FAILED: 'DOCUMENT_PROCESSING_FAILED',
  OCR_COMPLETED: 'OCR_COMPLETED',

  // AI & Document Intelligence
  AI_ANALYSIS_STARTED: 'AI_ANALYSIS_STARTED',
  AI_ANALYSIS_COMPLETED: 'AI_ANALYSIS_COMPLETED',
  AI_ANALYSIS_FAILED: 'AI_ANALYSIS_FAILED',
  ANALYSIS_VIEWED: 'ANALYSIS_VIEWED',

  // Phase 7: Tampering & Face Verification
  TAMPERING_ANALYSIS_STARTED: 'TAMPERING_ANALYSIS_STARTED',
  TAMPERING_ANALYSIS_COMPLETED: 'TAMPERING_ANALYSIS_COMPLETED',
  TAMPERING_ANALYSIS_FAILED: 'TAMPERING_ANALYSIS_FAILED',
  FACE_VERIFICATION_STARTED: 'FACE_VERIFICATION_STARTED',
  FACE_VERIFICATION_COMPLETED: 'FACE_VERIFICATION_COMPLETED',
  FACE_VERIFICATION_FAILED: 'FACE_VERIFICATION_FAILED',

  // Phase 8: Risk Scoring & Screening Intelligence
  RISK_ASSESSMENT_COMPLETED: 'RISK_ASSESSMENT_COMPLETED',
  SCREENING_STARTED: 'SCREENING_STARTED',
  SCREENING_COMPLETED: 'SCREENING_COMPLETED',
  SCREENING_FAILED: 'SCREENING_FAILED',

  // Watchlist & Validation
  WATCHLIST_ENTRY_CREATED: 'WATCHLIST_ENTRY_CREATED',
  WATCHLIST_ENTRY_DELETED: 'WATCHLIST_ENTRY_DELETED',
  DOCUMENT_VALIDATION_COMPLETED: 'DOCUMENT_VALIDATION_COMPLETED',

  // Screening & Forensics
  SCREENING_EXECUTED: 'SCREENING_EXECUTED',
  DOCUMENT_UPLOADED: 'DOCUMENT_UPLOADED',
  THREAT_FLAGGED: 'THREAT_FLAGGED',
  REPORT_GENERATED: 'REPORT_GENERATED',
};
